spring:
  datasource:
    name: lineMes_review
    url: jdbc:postgresql://192.168.1.5:5432/lineMes_review
    username: postgres
    password: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    filters: stat,slf4j
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select version()
    testQuery: select version()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandonedTimeout: 1800
    sqlScriptEncoding: UTF-8
    jta:
      enabled: true
      atomikos:
        properties:
          default-jta-timeout: 600000
          max-timeout: 600000
        datasource:
          jta-postgre:
            uniqueResourceName: lineMes_review
            xa-properties.url: jdbc:postgresql://192.168.1.5:5432/lineMes_review
            xa-properties.username: postgres
            xa-properties.password: "1"
            xa-properties.driverClassName: org.postgresql.Driver
            defaultJtaTimeount: 600000
            maxTimeount: 600000
            filters: stat,slf4j
            initialSize: 1
            minIdle: 1
            maxActive: 20
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select version()
            testQuery: select version()
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            minPoolSize: 3
            maxPoolSize: 25
            borrowConnectionTimeOut: 30
            maxTimeOut: 0
            loginTimeout: 30
            removeAbandonedTimeout: 1800
            #          max_prepared_transactions: 10
            pinGlobalTxToPhysicalConnection: true
            xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          jta-sqlserver:
            uniqueResourceName: NBMS_ERP_MES_SYNC
            #          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
            xa-properties.URL: jdbc:sqlserver://192.168.1.8:1433;DatabaseName=NBMS_ERP_MES_SYNC;pinGlobalTxToPhysicalConnection=true
            xa-properties.user: mEs
            xa-properties.password: mEs123
            defaultJtaTimeount: 600000
            maxTimeount: 600000
            #          xa-properties.defaultJtaTimeount: 600000
            #          xa-properties.maxTimeount: 600000
            pinGlobalTxToPhysicalConnection: true
            initialSize: 1
            minIdle: 1
            maxActive: 20
            maxTimeOut: 0
            testOnBorrow: false
            maxWait: 60000
            loginTimeout: 30
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1
            testQuery: SELECT 1
            testWhileIdle: true
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            minPoolSize: 3
            maxPoolSize: 25
            borrowConnectionTimeOut: 30
            removeAbandonedTimeout: 1800
            #          max_prepared_transactions: 10
            xa-data-source-class-name: com.microsoft.sqlserver.jdbc.SQLServerXADataSource

logging:
  pattern:
  #    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:%-4.4L){faint} %m%n'
  #    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}-%L : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  file: 'd:/traceability/logs/mes.log'
  level:
    com.hvisions.mes: warn