app:
  loginTimeoutSecs: 600
  excel:
    templatePath: classpath:template/
  firstDayOfWeek: 1 #周的第一天(1:周一 7:周日)
  interfaceUrl: http://localhost:8888/

server:
  port: 8888
  context-path: /
web:
  uploadPath: C://quality_traceability_system//upload/
  picPath: ../lineMes_eqpt/src/main/resources/static/upload/
  localhost: http://localhost:80/
  cAccId: 291

spring:
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.uploadPath}
  mail:
    host: smtp.qq.com
    #    host: smtp.163.com
    username: 861964579@qq.com
    #    username: 18051457236@163.com
    password: jgxenuxdbmibbdec
    properties:
      mail:
        default-encoding: UTF-8
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml,classpath*:sqlServerMapper/*.xml
  typeAliasesPackage: com.hvisions.mes.domain
  global-config:
    id-type: 0 #AUTO->`0`("数据库ID自增") INPUT->`1`(用户输入ID") ID_WORKER->`2`("全局唯一ID") UUID->`3`("全局唯一ID")
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


hvisions:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10
