spring:
  datasource:
    name: lineMes_review
    url: jdbc:postgresql://47.98.221.77:5432/lineMes_in_use
    username: postgres
    password: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    jta:
      enabled: true
      atomikos:
        datasource:
          jta-postgre:
            uniqueResourceName: lineMes_review
            xa-properties.url: jdbc:postgresql://47.98.221.77:5432/lineMes_in_use
            xa-properties.username: postgres
            xa-properties.password: "1"
            xa-properties.driverClassName: org.postgresql.Driver
            xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          jta-sqlserver:
            uniqueResourceName: NBMS_ERP_MES_SYNC
            xa-properties.URL: jdbc:sqlserver://47.98.221.77:1433;DatabaseName=NBMS_ERP_MES_SYNC;pinGlobalTxToPhysicalConnection=true
            xa-properties.user: dpeng
            xa-properties.password: "123456"
            xa-data-source-class-name: com.microsoft.sqlserver.jdbc.SQLServerXADataSource

logging:
  pattern:
  #    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:%-4.4L){faint} %m%n'
  #    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39}-%L : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
  console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
  file: 'd:/traceability/logs/mes.log'
  level:
    com.hvisions.mes: DEBUG
    druid.sql.Statement: DEBUG
    druid.sql.ResultSet: DEBUG
    org.springframework.boot: debug
    com.atomikos: error